DROP TABLE IF EXISTS burgers_db;
CREATE DATBASE burgers_db;
USE burgers_db;
CREATE TABLE burgers(
  'id' INT NOT NULL AUTO_INCREMENT,
  'burger_name' VARCHAR(25),
  'devoured' BOOLEAN NOT NULL DEFAULT 0,
  'date' TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY('id')
);
